apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
spec:
  replicas: 4
  selector:
    matchLabels:
      app: my-nginx-app
  template:
    metadata:
      name: nginx-rs-pods
      labels:
        app: my-nginx-app
    spec:
      containers:
      - image: nginx
        name: nginx-app-cont
        ports:
        - containerPort: 8080
          protocol: TCP
        command: ["/bin/bash","-c"]
        args:
        - date >> /usr/share/nginx/html/index.html;
          



